# .github/workflows/release.yml
name: Release App

on:
  push:
    tags:
      - 'v*' # Questo workflow si attiva quando fai un push di un tag che inizia con 'v' (es. v1.0.1)

jobs:
  build_and_release:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build and Publish
        run: npm run dist
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
